Repository thoth-station/srcops-testing, pull requests merged in 2018-10, with the labels that each got.

#56 Automatic update of dependency pytest from 3.8.1 to 3.8.2
  Pipfile.lock
Labels: bot

#62 adding zuul jobs to run coala and pylint
  .zuul.yaml
  coala.yaml
  pylint.yaml
Labels: size/M, size/S

#64 Automatic update of dependency pytest from 3.8.2 to 3.9.1
  Pipfile.lock
Labels: bot

#67 Release of version 2018.10.18
  version.py
Labels: bot, size/XS

#66 Release of version 2018.10.17
  version.py
Labels: approved, bot, size/XS

#68 Automatic update of dependency pytest from 3.9.1 to 3.9.2
  Pipfile.lock
Labels: bot

#69 Automatic update of dependency pytest from 3.9.2 to 3.9.3
  Pipfile.lock
Labels: bot
