Repository thoth-station/srcops-testing, pull requests merged in 2019-06, with the labels that each got.

#110 test zuul webhook trigger build with multiple jobs
  .zuul.yaml
Labels: approved, size/S

#111 fix up the namespace in testing job
  .zuul.yaml
Labels: size/XS

#112 Do another trigger build test with result-api
  .zuul.yaml
Labels: approved, size/S

#113 Automatic update of dependency pytest from 4.5.0 to 4.6.2
  Pipfile.lock
Labels: bot

#114 Release of version 2019.0.0
  version.py
Labels: approved, bot, size/XS

#115 more testing for build trigger
  .zuul.yaml
Labels: size/S

#116 Revert "more testing for build trigger"
  .zuul.yaml
Labels: size/S

#117 Automatic update of dependency pytest from 4.6.2 to 4.6.3
  Pipfile.lock
Labels: bot

#118 test webhook for metrics-exporter
  .zuul.yaml
Labels: size/XS

#119 more test on metrics-exporter webhook
  .zuul.yaml
Labels: size/XS

#120 more test on metrics-exporter webhook
  .zuul.yaml
Labels: size/XS

#122 zuul can handle W.I.P. for us...
  .zuul.yaml
Labels: size/XS

#128 Release of version 2019.06.26
  version.py
Labels: bot, size/XS

#129 Automatic update of dependency pytest from 4.6.3 to 5.0.0
  Pipfile.lock
Labels: bot
